name              'packer_templates'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'Apache-2.0'
description       'Installs/Configures packer_templates'
issues_url        'https://github.com/osuosl/packer-templates/issues'
source_url        'https://github.com/osuosl/packer-templates'
chef_version      '>= 16.0'
version           '1.0.0'

depends 'dnf-automatic'
depends 'line'
depends 'yum-cron'
