name             'openstack_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures openstack_test'
long_description ''
version          '0.1.0'
depends          'osl-ceph'
depends          'osl-openstack'
depends          'osl-docker'
depends          'hostsfile'
